# Generated by Django 4.2.6 on 2023-10-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='WeFix_Zim Blog Site ', max_length=255),
        ),
    ]
